spring.application.name=academico
# 1. Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_academico
spring.datasource.username=${USUARIO}
spring.datasource.password=${SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configurações do Hibernate (JPA)
# Define o schema padrão como 'academico' para o Java saber onde procurar as tabelas
spring.jpa.properties.hibernate.default_schema=academico

# Define como o Hibernate deve se comportar com a estrutura do banco.
# Como as tabelas já existem, usamos 'validate' apenas para conferir se está tudo certo.
spring.jpa.hibernate.ddl-auto=validate

# Mostra no console do IntelliJ os comandos SQL que o Spring gera
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true